FROM tensorflow/tensorflow:latest-gpu-py3
MAINTAINER Thibaud LE GALL "legallthib@wanadoo.fr"

USER root


# Setting up linux environment
RUN dpkg --add-architecture i386

RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
RUN apt-get update && apt-get install -y \
	software-properties-common \
	supervisor \
	ttf-mscorefonts-installer \
	wget
	
# Installing wine
RUN wget -qO - https://dl.winehq.org/wine-builds/winehq.key | apt-key add -
RUN apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main'
RUN apt-get install --install-recommends winehq-stable -y

# Make working directory, give permissions and access it
RUN mkdir -p /home/nsml/
RUN chmod -R 777 /home/nsml
RUN cd /home/nsml/

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]