FROM tensorflow/tensorflow:latest-gpu-py3
MAINTAINER Thibaud LE GALL "legallthib@wanadoo.fr"

USER root

# Make Directory, give permissions and access it
RUN mkdir -p /home/AI_core/
RUN chmod -R 777 /home/AI_core/
RUN cd /home/AI_core/
WORKDIR /home/AI_core/

# Install ubuntu dependencies
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
		cmake \
		discover \
		dos2unix \
		git \
		hwinfo \
		libxext-dev \
		libxrender-dev \
		libxtst-dev \
		mdetect \
		mpich \
		mpich-doc \
		read-edid \
		software-properties-common \
		unzip \
		wget \
		xorg
	
# Installing Python dependencies
RUN mkdir code
COPY requirements.txt code/
RUN pip install -r code/requirements.txt &&\
	python -m ipykernel.kernelspec
	
# Similar to the above, but with just the development-specific requirements
#COPY requirements-dev.txt /code/
#RUN pip install -r requirements-dev.txt
	
# Preparing an SSH server to interpret python
RUN apt-get update \
	&& apt-get install -y openssh-server netcat \
	&& mkdir /var/run/sshd \
	&& echo 'root:password' | chpasswd \
	&& sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Install StarCraftII (headless version)
RUN wget -q http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.0.2.zip

# Uncompress StarCraftII
RUN unzip -P iagreetotheeula -d /home/AI_core/ SC2.4.0.2.zip 

# Download StarCraftII Maps
RUN wget -q https://github.com/deepmind/pysc2/releases/download/v1.2/mini_games.zip 

RUN wget -q http://blzdistsc2-a.akamaihd.net/MapPacks/Melee.zip
RUN wget -q http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season4.zip
RUN wget -q http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season3.zip
RUN wget -q http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season2.zip
RUN wget -q http://blzdistsc2-a.akamaihd.net/MapPacks/Ladder2017Season1.zip

# Uncompress zip files
RUN unzip mini_games.zip -d /home/AI_core/StarCraftII/Maps/
RUN unzip -P iagreetotheeula Melee.zip -d /home/AI_core/StarCraftII/Maps
RUN unzip -P iagreetotheeula Ladder2017Season4.zip -d /home/AI_core/StarCraftII/Maps/
RUN unzip -P iagreetotheeula Ladder2017Season3.zip -d /home/AI_core/StarCraftII/Maps/
RUN unzip -P iagreetotheeula Ladder2017Season2.zip -d /home/AI_core/StarCraftII/Maps/
RUN unzip -P iagreetotheeula Ladder2017Season1.zip -d /home/AI_core/StarCraftII/Maps/

# Delete zip files
RUN rm SC2.4.0.2.zip
RUN rm mini_games.zip
RUN rm Melee.zip
RUN rm Ladder2017Season4.zip
RUN rm Ladder2017Season3.zip
RUN rm Ladder2017Season2.zip
RUN rm Ladder2017Season1.zip

# Set up notebook config
COPY jupyter_notebook_config.py /root/.jupyter/

# Jupyter has issues with being run directly: https://github.com/ipython/ipython/issues/7062
COPY run_jupyter.sh /home/AI_core/

# Enable jupyter widgets
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

#Formating the file to ensure that it is readable to unix system
RUN dos2unix /home/AI_core/run_jupyter.sh

# Expose Ports for SSH(22), Flask (5000), TensorBoard (6006), Ipython (8888)
EXPOSE 22 5000 6006 8888

# Setup Working dir
RUN mkdir /home/AI_core/app

# Starting SSH service and jupyter notebook
CMD jupyter notebook --allow-root --no-browser --ip=0.0.0.0 & /usr/sbin/sshd -D & sleep 2 && jupyter notebook list > $logs_path/jupyter_logs.txt && /bin/bash